### PR TITLE
issue-7 First tests written

### PR DESCRIPTION
**Pull request by goDeni**

### CODE REVIEW

**Comment by goDeni** [comment]
Forgot add cago test in ci

**Comment by mikhailantoshkin** [comment]
LGTM, I think it could be beneficial to add property based testing at some point in the future with, for example, [arbitrary](https://crates.io/crates/arbitrary)

**Review by mikhailantoshkin — APPROVED** [review]
LGTM, I think it could be beneficial to add property based testing at some point in the future with, for example, [arbitrary](https://crates.io/crates/arbitrary)

**Comment by mikhailantoshkin** [comment]
cc @WindowGenerator

**Pull request merged**
